POST localhost:27401/auth/login
Content-Type: application/json

{"id":0,"login":"omega2","email":"","pass":"omega","role":"USER","token":""}

###
GET localhost:27401/api/read/tv_show


####
GET localhost:27401/api/creator/read/anime
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDM1MDExMzEsImV4cCI6MTcwMzU4NzUzMSwic3ViIjoib21lZ2EifQ.X0-PocJUy5QUIN_WuWDaZurhSmYDCRPHQuVk9HkJpli2avk69fJbcbVKzQZB1SChbjiBEr3V5tyHYWieTgsywA

###
GET localhost:27401/api/read/comic


###

GET localhost:27401/api/read/all_tags

###
GET localhost:27401/test/add

###
GET localhost:27401/api/read/anime/7


###
GET localhost:27401/test/comic

###
GET localhost:27401/test/anime
Content-Type: application/json

{
  "content": {
    "id": 0,
    "title": "t",
    "description": "desct",
    "posterPath": "path",
    "isColored": true
  },
  "studio": "studio name",
  "tags": [
    {
      "id": 1,
      "name": "GOVNO"
    },
    {
      "id": 2,
      "name": "PENIS"
    }
  ]
}