POST localhost:27401/auth/login
Content-Type: application/json

{"id":0,"login":"omega","email":"","pass":"omega","role":"USER","token":""}

###
GET localhost:27401/api/read/tv_show


####
GET localhost:27401/test/file
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDMyNTg4MzgsImV4cCI6MTcwMzM0NTIzOCwic3ViIjoiYWJvYmEifQ.3gnvuU-iO1ZmItmRA68TrC3jWla1jYFxLVc8uNQt0EMu_8KNJqbYVopOehUt6-GToyeBZS6oVGSVSuD9EU9u-w

###
GET localhost:27401/api/read/anime


###

GET localhost:27401/api/read/all_tags

###
GET localhost:27401/test/add