POST localhost:27401/auth/register
Content-Type: application/json

{
  "id": 0,
  "login": "aboba3",
  "email": "aboba3",
  "pass": 1234,
  "role": "USER"
}


####
GET localhost:27401/test/anime
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDMyNTg4MzgsImV4cCI6MTcwMzM0NTIzOCwic3ViIjoiYWJvYmEifQ.3gnvuU-iO1ZmItmRA68TrC3jWla1jYFxLVc8uNQt0EMu_8KNJqbYVopOehUt6-GToyeBZS6oVGSVSuD9EU9u-w